### ISSUE TITLE
Is this adding or replacing music?

### ISSUE THREAD

**Issue by paulcobbaut** [LUISDASARTIMANHAS/OpenTTD-OST-Factorio-version#3]
I think it would be useful to mention in the readme whether this adds the OpenTTD music, or completely replaces all Factorio music. Or can it be configured in a ratio using mod settings?

**Comment by LUISDASARTIMANHAS** [comment]
You are right! But the mod itself already does a self-balance so as not to replace the game's music and not just stay with openttd

**Comment by paulcobbaut** [comment]
Thanks!
